### ISSUE TITLE
Error to run example file

### ISSUE THREAD

**Issue by reactiver001** [cycyup/crack_geetest#2]
When try run example file have this error 

python3 geetest.py
Traceback (most recent call last):
  File "/Users/Desktop/ideas/crack_geetest/geetest/geetest.py", line 73, in <module>
    geetest_crack()
  File "/Users/Desktop/ideas/crack_geetest/geetest/geetest.py", line 51, in geetest_crack
    data_stream = io.BytesIO(image.content)
NameError: name 'io' is not defined

thanks

**Comment by reactiver001** [comment]
Hello

I try now but dont work , possible send me example for run ?

first run api.py and next run geetest_crack.py , correct?
Great work

jager ***@***.***> escreveu no dia quarta, 9/03/2022 à(s)
15:23:

**Comment by cycyup** [comment]
No, only run geetest_crack.py, but you should download api.py too, geetest_crack.py import the function from api.py

**Comment by reactiver001** [comment]
Traceback (most recent call last):
  File "/Users/crack_geetest/geetest/geetest_crack.py", line 4, in <module>
    from geetest.api import get_w
ModuleNotFoundError: No module named 'geetest'

When run geetest_crack.py have error import module
